### ISSUE TITLE
fake legos

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#1]
The bottom of the lego model is not accurate :(
<img width="529" alt="screenshot 2018-01-29 11 18 25" src="https://user-images.githubusercontent.com/1502180/35520842-3628fa0e-04e6-11e8-9d6f-4372155e270a.png">

**Comment by RELNO** [comment]
We went for cheaper knockoffs, this is what we got :/

**Comment by RELNO** [comment]
solved with more polygons 
https://github.com/CityScope/cityscope.github.io/commit/a113a6c4bb4b51da016561b736612f5905bd1735
