### ISSUE TITLE
table CAD files

### ISSUE THREAD

**Issue by dunland** [CityScope/cityscope.github.io#17]
Hello everyone,
I can't imagine to be the first one to ask, yet I couldn't find any information on this:
Do you provide the CAD files for the table setup as well? There are great DRAWING-ASSEMBLY(.pdf) instructions in the repo, but to apply our own adjustments, we'd be happy to receive the raw CAD files!
Any place I forgot to browse?
Thanks in advance!

**Comment by RELNO** [comment]
Hi @dunland, we have some CAD instructions for panel laser cutting here https://github.com/CityScope/cityscope.github.io/tree/master/CS_Hardware/CS%20TABLE_KP_15/LASERCUT%20Drawings, however not the whole table is in CAD unfortunately.
One thing to point out is that the PDF represents a specific varient of CityScope. In many (actually - most) other cases, tables are customized to fit a different scale or shape. If you're just testing things out, an acrylic surface on top of any frame would do the trick.

**Comment by dunland** [comment]
Thanks for the quick reply. In that case I guess I will have to redraw the measures as depicted in https://github.com/CityScope/cityscope.github.io/raw/master/CS_Hardware/CS%20TABLE_KP_15/DRAWING-ASSEMBLY.pdf and adjust it according to my needs.

**Comment by RELNO** [comment]
@LAAP can you share the Grasbrook frame drawing with @dunland? This is a newer version which is far larger and is designed to sustain intensive user interaction without interface to the scanning system

**Comment by RELNO** [comment]
@dunland please take a look at https://github.com/CityScope/cityscope.github.io/tree/master/CS_Hardware/CS%20TABLE_KP_15/CAD, thanks to the Karthik who designed the tables, this folder now holds CAD and 3D of the design. Hope this helps.
