### ISSUE TITLE
Cannot deploy build to GH-PAGES in this repo

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#18]
clean up this repo in alignment with the standalization effort

**Comment by RELNO** [comment]
@yasushisakai can you take a look at https://github.com/CityScope/cityscope.github.io/tree/%2337_cleanup and suggest a way to scroll between the upper viz and lower docs part?

**Comment by RELNO** [comment]
@yasushisakai can you help with solving this niche issue https://dev.to/javascripterika/deploy-a-react-app-as-a-github-user-page-with-yarn-3fka 
TLDR: on user page, there is no gh-pages option, but all has to be deployed from master. I don't know if this will make things weird.

**Comment by RELNO** [comment]
@yasushisakai any input on this? I can merge the pull but then will have to hold a __SRC__ branch for the source, and the Master will be the build. It's not a pretty solution though

**Comment by yasushisakai** [comment]
Just breaking down the action points:

1. merge the `dev` to `master`
2. `build` inside `master` branch (in `/docs`?) 
3. commit & push `master`
4. check the url

I'm not sure about the CNAME stuff but let's see how that turns out.

@RELNO missing anything?

**Comment by RELNO** [comment]
I'm not sure I understand 1.
If you merge Dev to master you just have both Dev and master holding the same data, no? 
My understanding is that master should be only holding a built version (same as GH-pages in other repos)

**Comment by yasushisakai** [comment]
My thinking was `master` will show which version is actually being deployed, where the `dev` can be still be half baked and left for discussion.
Other than hurting your eyes, Git internally keeps only one copy of the file contents across branches, so duplicate things in `master` and `dev` won't hurt in terms of storage or performance.

**Comment by RELNO** [comment]
Sounds good -- do you want to try and deploy to see if this can work? I'm under the assumption that `master` has to have only the "dirty" build, but I'll be happy to stand corrected.

**Comment by yasushisakai** [comment]
but, if we choose, we can always delete the src part in the `master` (or create a pre-commit) and just leave the `doc` folder. To clarify, the `doc` is the meat right? or is at the `/root` level?

I'll dig in.

**Comment by RELNO** [comment]
`doc` must stay in `dev` as it is being read from there to the frontend.

**Comment by yasushisakai** [comment]
The basic idea of [the site you mentioned earlier](https://dev.to/javascripterika/deploy-a-react-app-as-a-github-user-page-with-yarn-3fka) is the same for what I was thinking, but looking into her actual `user`.github.io repo:
https://github.com/JavaScriptErika
looks like her project lies at the repo root. Which is slightly different than our case having `cityscope` folder as the project root. Where does is the location of the md doc files relate to the built react app?

**Comment by RELNO** [comment]
I can move the content of `cityscope` to the `root` of `dev` but I don't think it's necessary since we're anyway building to another branch. 
As for the `doc`folder -- they are statically linked by the `md` parser, so they could be anywhere, they are never being added as part of the build:

```
export default () => {
    const [content, setContent] = useState();
    const { contentUrl } = useContext(AppContext);
    const globalDocsURL =
```
     
// this is the static link 
   **"https://raw.githubusercontent.com/CityScope/cityscope.github.io/dev/";**

```
    const thisDocURL = globalDocsURL + contentUrl;

    useEffect(() => {
        axios
            .get(thisDocURL, {
                mode: "no-cors",
            })
            .then((response) => {
                setContent(response.data);
            });
    }, [thisDocURL]);

    return (
        <div className="result-pane">
            <ReactMarkdown
                className="result"
                source={content}
                transformImageUri={(uri) =>
                    uri.startsWith("http") ? uri : `${globalDocsURL}${uri}`
                }
            />
        </div>
    );
};
```
