### ISSUE TITLE
Global structure of the organization

### ISSUE THREAD

**Issue by agrignard** [CityScope/cityscope.github.io#2]
This is still not converging.

What about having the Luis picture here for now and then converging together on something. Once this is agreed (doesn't mean it's the final version but at least its version 1.0) then no one can creat e a repository that doesn't fit with the proposal

**Comment by LAAP** [comment]
I agree with Arnaud. At the same time I was planning to add some basic indications about when to use "CS" and "CSL", etc. and about how to proceed when making a new repository (how to Label it. As an example: "CS_scan_unity")

**Comment by yasushisakai** [comment]
so the [software architecture](https://github.com/CityScope/cityscope.github.io/wiki/Software-Architecture) has the listing of scanning and categorization of similar functionalities? or is thing for something else?

**Comment by agrignard** [comment]
Well it's very high level it was to try to understand what kind of
architecture we want feel free to edit or remove it

**Comment by popabczhang** [comment]
Per the discussion with @agrignard, there might be more than 2 categories of repos. 

1) function module repos, e.g.: CS_Scanning, CS_Simulation, CS_CityIO_Backend, etc.; 
2) City Science Labs repos, e.g.: CSL_Shanghai, CSL_Andorra, etc.; 

Now we already have several repos in other categories: 

3) template project repos for single software with the complete function modules that can run by itself, e.g.: CS_CSharpScope_Template, CS_Rhino_Grasshopper_Template; 
4) repo for single software but only as specific modules, e.g.: CS_Simulation_GAMA; 
5) repo for single software, complete project for specific lab/location, e.g.: CS_CSharpScope_Andorra, CS_CSharpScope_BRT; 

Obviously, it's getting chaotic already. I believe we need to sit together to converge on a systematic structure before we create any more repos.

**Comment by popabczhang** [comment]
some quick thoughts: 

- Should we have CSL_MIT_Media_Lab and put all the Media Lab project (e.g.: CS_CSharpScope_BRT) under it? If so, will the repo be too huge? 
- Should software specific module repos (e.g.: CS_Simulation_GAMA) be put under module repos (e.g.: CS_Simulation)?
- Should we put software specific, project specific repos (e.g.: CS_CSharpScope_Andorra, CS_CSharpScope_BRT) under CSL repos? Or we should have project specific repos anyway? 
- Can we use a smarter name system so that we can have more flexibility in orgnizing the repos?

**Comment by agrignard** [comment]
This issue was open before we agree on the global structure so I should have close it actually.

It's not chaotic it is what we propose for now and it gives enough freedom to someone that want to create a repository. That's what you wanted right?. So let's give it a try 

The current structure is this one and it's documented and agreed 
https://github.com/CityScope/cityscope.github.io/wiki
