### ISSUE TITLE
CS Types - Question

### ISSUE THREAD

**Issue by MarkusElKatsha** [CityScope/cityscope.github.io#21]
Hello Ronan - The above is great!

I have a few questions/comments. Please note the following:

Comment: should a type include information about utilization or capacity (in the same way we use S, M, or L on the Volpe table)? I do not think it should be S,M,L, but we could use a person/meter or some scale factor to add to the definition of components within a type. IE: For a given land-use, we need to outline how they are aggregated? Is it 1 unit or 3 units/floor.

Comment: there will never be an economic activity without a land-use, but there can be land-uses without economic activity. Would it be better to format or organize the data in a way that associates a NICS code of each land-use, when a NICS code is available?

Question: what does the "P" above each land-use mean?

**Comment by doorleyr** [comment]
Closing as this is duplicating discussion in another issue: https://github.com/CityScope/cityscope.github.io/issues/15
