### ISSUE TITLE
Data types for docs

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#26]
related to #15

I've briefly checked @doorleyr's ronan branch, specifically [this](https://github.com/CityScope/cityscope.github.io/blob/ronan/docs/md/Land-Use-Types.md) file and @RELNO's CityScope/CS_CityScopeJS [readme](https://github.com/CityScope/CS_cityscopeJS). and I have a question.

for writing up the data formats, how much strictness do we want? Essentially it's a JSON, so the [types](https://www.json.org/json-en.html) provided are:

* `null`
* `true`
* `false`
* Number
* String
* Array
* Object

Specifying each element on this level of granularity is something we can aim, but was wondering if it's useful if we go deeper.

<details><summary>1. numbers </summary>

```
"NICS" : 1212.50 // 1-1. int float mismatch
"NICS" : -1 // 1-2. int type mismatch
"latitude" : -2121.00 // 1-3. out of range
"rent" : "100 USD" // 1-4. ?? -> or "rentPerSquareMeters": {value: "100.01", unit: "sqm"}
```

</details>

<details><summary>2. how to handle null values</summary>

```
// 2-1. no NICS field.
"NICS" : [] // 2-2. empty arrays / objects
"NICS" : null // 2-3. null
"NICS" : [{}, [[], []], null] // 2-4. 2-2 and 2-3
```

</details>

Again, it's just JSON, so it's really up to the parser (and it's language) how to handle it.

Too much is stupid (`2-4`) and I think people can communicate to straiten things out, so I'm not too worried but what do you think @RELNO, @doorleyr, @agrignard?

**Comment by RELNO** [comment]
@yasushisakai thanks. Yes, that's exactly where your input can help. My attitude would be to be strict so that parsers would have it easier. This is b/c we have multiple points of contact with the data (FE, BE, modules..) and we would want to make sure they are always getting the right data.

**Comment by yasushisakai** [comment]
yeah, the frontend is by language design quite forgiving, but do you bump into situations that type checking or null's handled in a specific way will make your life easier?

``` javascript
if (table.NICS != null) {} // or
if (table.NICS.length != 0) {}
NICS = parseInt(table.NICS) || 0;
```

 I wonder what the module makers think?

just as a side note: https://github.com/json5/json5

**Comment by RELNO** [comment]
> just as a side note: https://github.com/json5/json5

![image](https://user-images.githubusercontent.com/14296774/83925854-336c8f00-a756-11ea-9ff6-7e5d8189ff72.png)

**Comment by RELNO** [comment]
@yasushisakai let's reopen if needed upon doc-ing cityIO
