### ISSUE TITLE
transfer cityIO docs/wiki into here

### ISSUE THREAD

**Issue by RELNO** [CityScope/cityscope.github.io#29]
@yasushisakai as discussed, please suggest the best way for you to include cityIO docs in here. The 2 options are: 1. simply move 2. copy here, and ask @crisjf to modify a GH action to keep in sync with your repo. 
I see [1] simpler and cleaner, but it's up to you.

**Comment by yasushisakai** [comment]
I'll move it.
I see it should be here right?
https://github.com/CityScope/cityscope.github.io/tree/new_docsite/docsite/docs/modules/cityio

 is there anything I neeed to do other than this, it looks like there is some front-matter format?
```
---
id:cityio
---
```

**Comment by RELNO** [comment]
Yes, there's a minor flag to let the framework know how to name the article. 
I think that based on https://cityscope.media.mit.edu/docs/general/CityScopeJS%20Ecosystem diagram, cityIO should have its own place as https://github.com/CityScope/cityscope.github.io/tree/new_docsite/docsite/docs/**BACKEND**/cityio, since it's agnostic to modules or frontend.

**Comment by crisjf** [comment]
@yasushisakai the action should also take care if that. Let me know where your `md` file lives and I'll point the action to that location and you won't have to worry about it anymore.

**Comment by yasushisakai** [comment]
ok, so if 
1. I have the md files living inside the cityio repo (accessible via `raw.githubusercontent`), @crisjf 's actions can automatically populate that to this repo?
or
2. I should still put it `this/repo/docsite/docs/backend/cityio`? and manually put the front-matter

I don't have strong opinions where to put it, just want one place to edit.

**Comment by crisjf** [comment]
The action does 1, and it also adds front-matter. It updated every day at midnight so any edits that you do to your master `md` file with documentation will be automatically synced here. Where is the file right now?

**Comment by yasushisakai** [comment]
currently have it on the wiki, but will move it inside the cityio repo then... I will let you know when I'm done

**Comment by crisjf** [comment]
We can also pull it from the wiki. Can you link it here?

**Comment by RELNO** [comment]
@yasushisakai thanks. As mentioned, it's really up to you. I personally skipped that process to simply put `md` in the meta-repo, and none in the sub-repos. Do keep in mind that @crisjf script (despite being reallllllly cool ), cannot handle future changes to files and folders locations. Also, `mdx` capabilities might not work.

**Comment by crisjf** [comment]
I looked at the wiki in the CityScope/CS_CityIO repo. Adding this block to the `pull_docs.yml` workflow should solve this issue. I'm happy to implement it if you guys are happy with it. 

```
- name: Update CS_CityIO
  run: bash .github/scripts/update.sh wiki/CityScope CS_CityIO docsite/docs/backend Home.md API.md Client-Examples.md
```

**Comment by yasushisakai** [comment]
@crisjf thanks, but I would like to use this opportunity to get rid of the wiki and centralize it for access. Another thing I do think it's saner to have the *original docs* closer to the actual code. This is not meant to be referenced by for me to maintain.

commit [5a1517](https://github.com/CityScope/CS_CityIO/commit/5a15174c0615adde34d0f56ade708e45d93d750f) has the .md files inside the https://github.com/CityScope/CS_CityIO repository. its inside the `docs/` ([here](https://github.com/CityScope/CS_CityIO/tree/master/docs))  folder under the project root.

What should I do next?

**Comment by crisjf** [comment]
Even better. Do you want to link all the `md`s? It looks like `Home.md`, `API.md`, and `Running-it-locally.md` are the important ones. If so, then add the following block to [this yml](https://github.com/CityScope/cityscope.github.io/blob/new_docsite/.github/workflows/pull_docs.yml) file. I wrote a short wiki on the syntax [here](https://github.com/CityScope/cityscope.github.io/blob/new_docsite/docsite/docs/general/docs_dev.md). 

```
- name: Update CS_CityIO
  run: bash .github/scripts/update.sh CityScope CS_CityIO docsite/docs/backend docs/Home.md docs/API.md docs/Running-it-locally.md
```

Once you've done this, every time you edit these three files, they will be automatically updated here. Let me know once you've done it and I'll take a look.

**Comment by crisjf** [comment]
Also, if you go to the Actions tab in this repo, you'll be able to run the workflow manually. Check [here](https://github.com/CityScope/cityscope.github.io/actions?query=workflow%3A%22Update+documentation+from+downstream+repos%22).

**Comment by RELNO** [comment]
@yasushisakai following @crisjf comment https://github.com/CityScope/cityscope.github.io/issues/29#issuecomment-696375682, if possible I suggest we consolidate cityIO docs into one large md file. This is b/c the new doc site works well with large md files, given the treemap structure. Also, one md makes it easier to embed in @crisjf service.

**Comment by yasushisakai** [comment]
got it! https://github.com/CityScope/CS_CityIO/commit/5ec07b1ecdf086efbf9a0c0587d196441311710d does this.

the single md file is located [here](https://github.com/CityScope/CS_CityIO/blob/master/docs/cityio_documentation.md) `/master/docs/cityio_documentation.md`

I'll go through typos and broken links and formatting once this workflow is established. Let me know what I'm missing

**Comment by crisjf** [comment]
I'll link it. @RELNO, just fyi the action and handle multiple mds. It just joins them into one single file keeping the order of the arguments in the action.

**Comment by RELNO** [comment]
@crisjf great, how's this file called at the end of the pipeline?

**Comment by crisjf** [comment]
All set, the file is synced here:
https://github.com/CityScope/cityscope.github.io/tree/new_docsite/docsite/docs/backend/CityIO

@RELNO please note the capital letters [C]ity[IO]

**Comment by RELNO** [comment]
Thanks both, closing
