### ISSUE TITLE
CityScope diagram/scheme

### ISSUE THREAD

**Issue by LAAP** [CityScope/cityscope.github.io#30]
Hi Everyone;

As commented on Friday, I have finished the first draft of my understanding of the CityScope diagram/scheme. It is a marged/update of 2 or 3 of the schemas that we already have:

![CityScope Schema](https://user-images.githubusercontent.com/19315213/94368868-8e831280-00b4-11eb-9aff-5c4f92021b81.jpg)

Please, let us know your thoughts

**Comment by RELNO** [comment]
@LAAP I'll close for now as we moved this discussion to slack. Reopen if necessary.

**Comment by LAAP** [comment]
OK
