### ISSUE TITLE
CityScope entry point meta_grid

### ISSUE THREAD

**Issue by agrignard** [CityScope/cityscope.github.io#33]
I am not sure this is the right place to right this issue.

I am working on making the bridge between GAMA and CityScope taking in example bricks.

This bridge has already been done with 2 projects corktown and grassbrook (which are still runing), in this 2 project I am using the ```meta_grid```property to initialize the table but i cannot see any ```meta_grid```field in the following url
in ```dungeonmaster```,

I am ok to point to another field what I'd like to be sure is to keep the retrocompatibility with what has already been implemented and keep it working. 

Maybe be meta_grid should be also change in corktown and grasbrook?

**Comment by RELNO** [comment]
The field that is constantly updating is `GEOGRIDDATA`.  The static `GEOGRID` never changes. This is explanied here https://cityscope.media.mit.edu/docs/modules/Brix/Brix#lets-talk-data-input

**Comment by agrignard** [comment]
Yep what I don't get is that Detroit still have it (but not grasbrook)
https://cityio.media.mit.edu/api/table/corktown/meta_grid

Do we consider that Detroit is not totaly compatible with the current API?

**Comment by RELNO** [comment]
@agrignard cityIO do not remove old endpoints in a table, so it might still be there. 
Also, @yasushisakai database recently restored very old versions of the tables, so it might be there since last time you were working on it.

**Comment by agrignard** [comment]
Ok I see so should we consider corktown as deprecated?

**Comment by doorleyr** [comment]
The fields that are needed are GEOGRID and GEOGRIDDATA. meta_grid shouldn't be there any more. I think what happened is cityIO crashed a while ago and then rebooted with a very old version of the corktown table data. I then added GEOGRID and GEOGRIDDATA.

**Comment by RELNO** [comment]
> https://dl.acm.org/doi/abs/10.1145/3334480.3382809

no

**Comment by RELNO** [comment]
> Ok I see so should we consider corktown as deprecated?

no, it's up and running

**Comment by doorleyr** [comment]
Actually, I'm just looking at the corktown table now. It was fine a week or so ago but it's been reset to a very very old table state.

**Comment by RELNO** [comment]
@doorleyr this is due to cityIO backup system which repeatedly falls back to very old states. @yasushisakai, can you please advise?

**Comment by agrignard** [comment]
Ok thanks @doorleyr it makes sense now, there is still meta_grid but it's not used, I Changed my model to geogrid
https://github.com/CityScope/CS_Simulation_GAMA/commit/3bf421142409cfa36de2d6d88796d1f189bcbe77
