### ISSUE TITLE
GEOGRID vs GEOGRIDATA

### ISSUE THREAD

**Issue by agrignard** [CityScope/cityscope.github.io#34]
In this table https://cityio.media.mit.edu/api/table/dungeonmaster/

Inside GEOGRID  each block has this properties
`````
"properties":{"color":[106,61,154],"height":4,"interactive":"Web"}
`````
and inside GEOGRIDDATA each block has this properties
`````
{"color":[255,255,51],"height":4,"id":0,"interactive":"Web","name":"Residential"}
`````

Do we need to repeat the information in both field? Isn't it redundant? Also the color value are different

**Comment by crisjf** [comment]
It is redundant, but it gives you the option of querying `GEOGRID` only once because it never changes and just calling `GEOGRIDDATA` when you detect the table update. Ignore the `properties` in `GEOGRID` and use the ones in `GEOGRIDDATA`. `GEOGRID` should be used when you need the coordinates of the table (you need them only at init) and to get the type definitions under `GEOGRID/properties`.

**Comment by RELNO** [comment]
Yes, as @crisjf mentioned the GEOGRID is state "0" of this table (i.e taboola rasa). Later states are GEOGRIDDATA

**Comment by agrignard** [comment]
OK

And is it necessary to store state 0 properties in GEOGRID? I mean in term of storing size (there was a time we were arguing wether we should use int or float to save space;-) )

Also Instead of writing  issue for this kind of question  is there an entry point for the meta structure of this json so I can look at it before to post an issue?

**Comment by RELNO** [comment]
> And is it necessary to store state 0 properties in GEOGRID? 

It's not about storing state 0. GEOGRID is the baseline data for both geometry and meta for each grid cell.  This is how we initiate a table with all its data in one place (vs the multi fields we used to have).
GEOGRIDDATA is lighter, as it's only meta without geometry (think= old `grid` field). This allow iterations in real time with small(ish) overhead.

**Comment by crisjf** [comment]
So as we think about the Handler agent in GAMA, the `GEOGRID` endpoint should be called on init, and the `GEOGRIDDATA` endpoint should be used for everything else.

**Comment by crisjf** [comment]
I think we can close this, right?

**Comment by RELNO** [comment]
Closing for now, @agrignard open at will.
