### ISSUE TITLE
Mismatch in types documentation  

### ISSUE THREAD

**Issue by RELNO** [CityScope/cityscope.github.io#38]
@LAAP as mention here,  https://github.com/CityScope/CS_cityscopeJS/issues/115, there's a slight inconsistency with how we describe "P" here: https://cityscope.media.mit.edu/docs/modules/Types%20System vs here: 
<img width="1287" alt="Screen Shot 2021-01-23 at 20 35 43" src="https://user-images.githubusercontent.com/14296774/105618887-9fba0280-5dba-11eb-8dee-f0e8cf7403aa.png">

**Comment by LAAP** [comment]
Hi @RELNO ,

Thanks for Asking. You are right, We could explain "proportion" a bit more in depth in the documentation. "Proportion" is equal to "P" and it is **"the percentage (%) of floors are devoted to a use in a "mixed use building/type"**. A 30% of a uses it is equal to "P": 0.3

However it is explained in "[Mixed use building](https://cityscope.media.mit.edu/docs/modules/Types%20System/#mixed-use-building)"

<img width="866" alt="Screen Shot 2021-01-25 at 9 37 04 AM" src="https://user-images.githubusercontent.com/19315213/105720280-42749d00-5ef1-11eb-9d6b-f661e9fcbde0.png">

**Comment by RELNO** [comment]
thanks -- can you update the docs in accordance? in terms of data format "P" and "proportion" are not the same as @takesei pointed out. I can fix the docs myself, but I don't have access to images.

**Comment by LAAP** [comment]
@RELNO , Sure I will do it ASAP. 
Pease, can you explain a bit more, the action needed when you say: _"in terms of data format "P" and "proportion" are not the same as @takesei pointed out."_ ? 

@takesei says: _"This topic isn't covered in the document (https://cityscope.media.mit.edu/docs/modules/Types%20System) (or maybe changing its name to "P" value??), so I'm a little confused."_

I think that he maybe using an old version of the code (Maybe Corktown?) before the final "unification", where "proportion" was still as the way of referring to "P". Isn't it?

**Comment by RELNO** [comment]
> I think that he maybe using an old version of the code (Maybe Corktown?) before the final "unification", where "proportion" was still as the way of referring to "P". Isn't it?

Yeah, I think that's the reason. It's basically making sure we're all on the same page in term of the data format we exchange between the modules and the FE/BE. Thanks!

**Comment by crisjf** [comment]
This is a documentation change alone, right? Or does something need to change in the way we parse the data?

**Comment by RELNO** [comment]
> This is a documentation change alone, right? Or does something need to change in the way we parse the data?

 I suspect (hope!) so.

**Comment by LAAP** [comment]
@crisjf , It is just a clarification at the Documentation. No worries!
