### ISSUE TITLE
Very naughty of you [also cool. also, lower framerate] 

### ISSUE THREAD

**Issue by RELNO** [CityScope/cityscope.github.io#4]
<img width="255" alt="screen shot 2018-03-13 at 21 20 13" src="https://user-images.githubusercontent.com/14296774/37378181-7eda9dc6-2704-11e8-8fef-167ce12cd438.png">

**Comment by yasushisakai** [comment]
[this software is cool](http://ephtracy.github.io/)

**Comment by RELNO** [comment]
I'll allow it.
