### ISSUE TITLE
Doc for backend still lists miragecity

### ISSUE THREAD

**Issue by crisjf** [CityScope/cityscope.github.io#45]
Not sure if this is the right repo to post this issue, but I noticed we haven't updated the hostname for the examples in the API documentation. It still reads `miragecity` which was the test server. 

https://cityscope.media.mit.edu/backend/API

**Comment by yasushisakai** [comment]
56790c5b10edbd0e7d6a170fadf5d4e7d3b0ca40 updates this... do I need to build the site..?

**Comment by RELNO** [comment]
@yasushisakai yes, that's a major (yet well hidden) drawback of this framework. I was hoping it's an md=>deploy kind of docsite, but for now we can try and set up an automated GH action to build with every master commit. @crisjf tried that before but I cannot recall why it failed.

**Comment by crisjf** [comment]
it got complicated and I dropped it

will definitely revisit it once I get my life back :)

**Comment by yasushisakai** [comment]
it wasn't too bad.... :)

```
git push -u origin new_docsite && yarn install && yarn build && export GIT_USER=yasushisakai && export USE_SSH=true && yarn deploy
```
(edited script error)

**Comment by RELNO** [comment]
@yasushisakai care to take a shot into github actions?

**Comment by crisjf** [comment]
This one
https://github.com/CityScope/cityscope.github.io/blob/new_docsite/.github/workflows/build_site.yml
