### ISSUE TITLE
Name of tools are too abstract

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#5]
This is subjective, but I feel creative alternatives are needed for following repo names.

If things are combined separate the functionalities to single repositories. If it needs to be linked, use another repo that uses submodules(recommended) or a readme to indicate the dependencies.

CS_Toolbox
CS_Hardware
\*\*Template
CS_CSharpScope_\* (with the exception of BRT)
CS_DataVisualization

**Comment by RELNO** [comment]
@yasushisakai any alternative naming suggestions?  
> If things are combined separate the functionalities to single repositories.

This might allow dozens of repos, each with minimal code -- is this something we want?

**Comment by yasushisakai** [comment]
naming proposals, Note I'm not aware of these programs so, forgive me if I'm acting arrogant.

CS_Projection_Mapping_JS
CS_Hardware_Specs
CS_CSharpScope
CS_CSharpScope_* (ultimately a branch but we have the other issue in consideration...)
CS_DataVisualization (I have no idea what this is)

I guess we want to experiment how we feel if we have so much tiny code repos, after all we won't perceive it if it doesn't get updated that often. ping @agrignard 

but some things we can do to be a little bit slimmer.
- if its one short script I would leave it as a gist
- multiple files and dependencies, but less significant impact, keep it in a personal account

**Comment by agrignard** [comment]
CS_DataVisualization was an empty shell at the very beginning to host something like andorra_RNC in a simple mapbox/carto/etc generic way. 

I see that @doorleyr put some stuff here but not sure if it's relevant

**Comment by doorleyr** [comment]
Regarding, CS_DataVisualization I agree it should be renamed. @agrignard the stuff I put in there is a dashboard for visualisation of mobility based on telecoms data. It's currently being used for the RNC but can easily be adapted for Cuebiq, TalkingData etc. So maybe it can be something like CS_MobilityDashboard or CS_TeleMobility?

**Comment by yasushisakai** [comment]
add RNC? or its not limited to that
