### ISSUE TITLE
MIT Disclosure procedure

### ISSUE THREAD

**Issue by agrignard** [CityScope/cityscope.github.io#6]
We have to work on that. Assuming that every repo has a licence it should be doable 

https://tlo.mit.edu/disclose-protect-your-intellectual-property/disclosure-faqs

**Comment by RELNO** [comment]
**UPDATE: This must be done PRIOR to putting the tools online!** 
This is the form we should all use: 
http://ipsw.media.mit.edu/create/

**Comment by yasushisakai** [comment]
No action or change on [policy](https://github.com/CityScope/cityscope.github.io/wiki/About-Licences) at this point.
