### ISSUE TITLE
merging JS and Backend

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#8]
We see an emerging ecosystem  of the Javascript Suite that @RELNO has been working, we would like to think about how we structure an one-stop solution using (only) JS.

- no external downloads (like Unity, Rhino)
- cross platform
- minimal configuration of the camera 
- various visualizations

@popabczhang  @agrignard  @doorleyr  @RELNO  @LAAP

**Comment by doorleyr** [comment]
I've also been working on real-time modelling and vis of O-D flows and traffic flows in response to changes in CityIO using JS with a Python server. @LAAP also has been working on radar plot using JS with a Processing server. We should think about consolidating all of these things.

![screen shot 2018-04-17 at 18 42 50](https://user-images.githubusercontent.com/7722116/38902601-3b7e6662-426f-11e8-9991-7c6ededf0ec8.png)

**Comment by yasushisakai** [comment]
I hope to raise this on the next (actually mono weekly, not so much) biweekly meeting

**Comment by popabczhang** [comment]
That make whole a lot of sense. Ariel's effort of "JSlize" CityScope was
also a promising demonstration. Yet we still have a lot to do before it
became a complete CityScope system. As a "baby"(term credit: Luis) in JS, I
wonder if someone could do a "getting started" tutorial about JS basics and
CityScope relavent libraries/resources? That would be very helpful.

**Comment by LAAP** [comment]
I am with @doorleyr and @yasushisakai, let's talk about this at our next meeting.

Thank you @popabczhang! Most of the heavy lifting was made by @lucascassiano, but I keep learning. Regarding the "getting Started" I totally agree with you! I think that it could be super cool!
