### ISSUE TITLE
procedure for adding repos in this org

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/cityscope.github.io#9]
This is the proposed procedure of adding new repositories to this github Organization. The reason behind this is to constrain the number of repo's.

1. First develop your code in your own personal account
2. Once you have the initial version (working) discuss collectively whether it's worth it having it official
3. If approved, we add it on the list

**Comment by RELNO** [comment]
Agreed

**Comment by yasushisakai** [comment]
The contradiction was that, we started to have no constrain on how we add repo's (to have an open community), but the organization was unclear about the privilege who gets which rights, which constrains who can add (closed). (Although, I thought I had it clear on the wiki)

The proposal is to have a standard and democratic procedure to add repo's so each time we are sure what to add.

**Comment by yasushisakai** [comment]
(Me personally I don't think having a lot of repo's is a problem, if we have a clear enough entry point to new comers.)

**Comment by yasushisakai** [comment]
but I agree.

**Comment by popabczhang** [comment]
> 1. First develop your code in your own personal account
> 2. Once you have the initial version (working) discuss collectively whether it's worth it having it official
> 3. If approved, we add it on the list

I agree with the new procedure. A good balance.

**Comment by yasushisakai** [comment]
We have collectively decided to make it free for every member to add, let natural selection (metabolism) make its way. @RELNO have also suggested to have a clean up session annually.
